### ISSUE TITLE
Specify Apps

### ISSUE THREAD

**Issue by neo-neo1** [scottmconway/notifikator#3]
Thanks for this fork.

Would it be possible to have a feature in the Android app to disable/enable which apps send notifications? Been earning to use this.

Thanks in advance

**Comment by scottmconway** [comment]
Dupe of #1

**Comment by scottmconway** [comment]
@neo-neo1 a graphical app picker has been implemented in the latest release!

**Comment by neo-neo1** [comment]
> [@neo-neo1](https://github.com/neo-neo1) a graphical app picker has been implemented in the latest release!

Thanks for adding it, just tried it. Unfortunately only System apps are shown. No User installed apps are shown. Maybe another 3 years and we'll get there finally? 😘

**Comment by scottmconway** [comment]
That would be due to the app missing the `QUERY_ALL_PACKAGES` permission. Fixed in v1.3.1!
